"""empty message

Revision ID: 159139c5ac25
Revises: 8a0e9cc0f65c
Create Date: 2023-10-29 19:56:39.138806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159139c5ac25'
down_revision = '8a0e9cc0f65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('characeteres_id', sa.Integer(), nullable=False),
    sa.Column('name_people', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=80), nullable=False),
    sa.Column('born_date', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('characeteres_id'),
    sa.UniqueConstraint('name_people')
    )
    op.create_table('planet',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('name_planet', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=80), nullable=False),
    sa.Column('climate', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('planet_id'),
    sa.UniqueConstraint('name_planet')
    )
    op.create_table('fav__people',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('characeteres_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characeteres_id'], ['people.characeteres_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'characeteres_id')
    )
    op.create_table('fav__planet',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.planet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav__planet')
    op.drop_table('fav__people')
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
